-- 008_storage_buckets.sql
-- Storage buckets. avatars/post-media/story-media/reel-media are public-read
-- (typical for a social feed); chat-attachments and school-documents are
-- private and require a signed URL / RLS-gated read.

insert into storage.buckets (id, name, public)
values
  ('avatars', 'avatars', true),
  ('post-media', 'post-media', true),
  ('story-media', 'story-media', true),
  ('reel-media', 'reel-media', true),
  ('chat-attachments', 'chat-attachments', false),
  ('school-documents', 'school-documents', false)
on conflict (id) do nothing;

-- Public buckets: anyone authenticated can read; only the owner (folder
-- named after their user id) can write to their own path.
create policy "public_media_read"
  on storage.objects for select
  to authenticated
  using (bucket_id in ('avatars', 'post-media', 'story-media', 'reel-media'));

create policy "public_media_write_own_folder"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id in ('avatars', 'post-media', 'story-media', 'reel-media')
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "public_media_update_own_folder"
  on storage.objects for update
  to authenticated
  using (
    bucket_id in ('avatars', 'post-media', 'story-media', 'reel-media')
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "public_media_delete_own_folder"
  on storage.objects for delete
  to authenticated
  using (
    bucket_id in ('avatars', 'post-media', 'story-media', 'reel-media')
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- Private buckets: owner-folder read/write only. Sharing a chat attachment
-- with the other participant should go through a signed URL generated by a
-- server-side call that has already checked conversation membership.
create policy "private_media_owner_read"
  on storage.objects for select
  to authenticated
  using (
    bucket_id in ('chat-attachments', 'school-documents')
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "private_media_owner_write"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id in ('chat-attachments', 'school-documents')
    and (storage.foldername(name))[1] = auth.uid()::text
  );
